controllers/ClassroomController.php
<?php

namespace app\controllers;

class ClassroomController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionClass($classname=null){
        return $this->render('classroom');
    }

    public function actionReportcard(){
        return $this->render('reportcard');
    }

}

views/classroom/classroom.php
<?php
use yii\helpers\Html;

$this->registerJsFile(
    '@web/js/classroom/index.js',
    ['depends' => [\app\assets\AppAsset::className()]]
);
$this->title = "Class";
?>

<div class="card card-default">
    <div class="card-header card-header-border-bottom justify-content-between">
        <h2> Class K2-01</h2>
        <ul>
            <li>Date: May 10, 2019 </li>
            <li>Today Subject: <a href="#" style="color:green;"> Opinion And Thougts</a></li>
        </ul>
    </div>

    <div class="card-body">
        <div class="row">
            <?php for ($i=0; $i<20;$i++){?>
            <!--begin-->



            <div class="col-lg-6 col-xl-3">
                <div class="card card-default p-4">

                    <?= Html::img('@web/img/student.png',
                         ['alt' => 'Emma Smith', 'class'=>'mr-3 img-fluid rounded']) ?>

                    <div class="media-body text-dark">
                        <h5 class="mt-0 mb-2 text-dark">Emma Smith</h5>
                        <ul class="list-unstyled">
                          
                            <li class="d-flex mb-1">
                                <i class="mdi mdi-checkbox-blank-circle-outline mr-1"></i>
                                <span>View 
                                    <?=Html::a("Report Card",['classroom/reportcard']);?>

                                </span>
                            </li>
                            <li class="d-flex mb-1">
                                <i class="mdi mdi-checkbox-blank-circle-outline mr-1"></i>
                                <span>View Biodata</span>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-primary btn-sm btn-block">Add Note</button>
                    </div>
                </div>
            </div>

            <!--end -->
            <?php }?>
        </div>

    </div>
</div>

views/classroom/subjectdetail.php
        <div class="modal fade" id="subjectdetaildlg" tabindex="-1" role="dialog" aria-labelledby="subjectdetaildlg"
            aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLarge">Subject Detail</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>  
                    <div class="modal-body">
                        <h2>Bahasa Indonesia 10</h2>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Course Academic Standard</th>
                                    <th>Standard Grading</th>
                                    <th>Course Grading</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="bold">
                                    <td >Bahasa Indonesia 10</td>
                                    <td class="text-center"></td>
                                    <td class="text-center">B</td>
                                </tr>
                                <tr>
                                    <td>Standar Keterampilan Berbahasa Indonesia (SKBI)</td>
                                    <td class="text-center">B</td>
                                    <td class="text-center"></td>
                                </tr>
                                <tr>
                                    <td>Membaca</td>
                                    <td class="text-center">B</td>
                                    <td class="text-center"></td>
                                </tr>
                                <tr>
                                    <td>Menyimak</td>
                                    <td class="text-center">A</td>
                                    <td class="text-center"></td>
                                </tr>
                                <tr>
                                    <td>Menulis</td>
                                    <td class="text-center">C</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>Berbicara</td>
                                    <td class="text-center">A</td>
                                    <td></td>
                                </tr>
                            </tbody>

                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">Detail</button>
                        <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>